#!/bin/bash

case $1 in
'shell')
    COMMAND='sh'
    ;;
'install')
    COMMAND="npm ${@}"
    ;;
*)
    rm -rf ./site/*
    COMMAND='npm run localBuild'
    ;;
esac

docker run \
    --rm --interactive --tty \
    --volume="$(pwd):/eleventy" \
    --workdir="/eleventy" \
    --user="$(id -u):$(id -g)" \
    'node:21.6.2-alpine3.18' \
    ${COMMAND}
