#!/bin/bash

case $1 in
'shell')
    COMMAND='sh'
    ;;
*)
    rm -rf ./site/*
    OPTION="${1:-pipeline}"
    shift
    COMMAND="yarn ${OPTION} $@"
    ;;
esac

docker run \
    --rm --interactive --tty \
    --volume="$(pwd):/eleventy" \
    --workdir="/eleventy" \
    --user="$(id -u):$(id -g)" \
    'node:21.6.2-alpine3.18' \
    ${COMMAND}
